### PR TITLE
New Market Data API

### PR DESCRIPTION
**Pull request by Petersoj**
Adds functionality for [streaming](https://alpaca.markets/docs/api-documentation/api-v2/market-data/streaming/), [last quote](https://alpaca.markets/docs/api-documentation/api-v2/market-data/last-quote/), and [last trade](https://alpaca.markets/docs/api-documentation/api-v2/market-data/last-trade/).

### CODE REVIEW

**Comment by jessethouin** [comment]
lgtm

**Comment by Petersoj** [comment]
@jessethouin I'm going to do a bit more testing before this gets integrated. Thanks though 👍 Testing will be much easier after unit testing has been added.

**Comment by jessethouin** [comment]
I can work on that. I'll branch and let you know which classes I'm targeting. Do you have a list you're already working on?

**Comment by Petersoj** [comment]
@jessethouin For this PR, I am doing manual testing. I was referring to the [unittesting](https://github.com/Petersoj/alpaca-java/tree/unittesting) branch that will make testing much easier.

**Pull request merged**
