### PR TITLE
Add week and month timeframes

### PR DESCRIPTION
**Pull request by balajikandavel**
https://alpaca.markets/docs/api-references/market-data-api/stock-pricing-data/historical/#bars

### CODE REVIEW

**Comment by Petersoj** [comment]
@balajikandavel thanks for the PR. Looks good. I'll merge this and publish a patch release soon.

**Comment by balajikandavel** [comment]
@Petersoj  Can you get a patch release when possible. I am using polygon.io for weekly and monthly timeframes. This will help me to save $$ :)

**Comment by Petersoj** [comment]
@balajikandavel yes I can publish the patch release today. Thanks for the reminder. I'll keep you posted.

**Comment by Petersoj** [comment]
Published in [`9.1.4`](https://github.com/Petersoj/alpaca-java/releases/tag/9.1.4)! Thanks for your patience.

**Pull request merged**
