### PR TITLE
Fix Fractional Market Order

### PR DESCRIPTION
**Pull request by jc-gomes**

### CODE REVIEW

**Comment by Petersoj** [comment]
Looks good. I will merge this and publish a patch release soon. Thanks for your contribution!

**Comment by jc-gomes** [comment]
> Looks good. I will merge this and publish a patch release soon. Thanks for your contribution!

Thank you!

**Comment by jc-gomes** [comment]
Please update this.

**Comment by Petersoj** [comment]
I will be updating this library this week. Thanks for your patience.

**Pull request merged**
