### PR TITLE
Add corporate actions and news endpoints for #118

### PR DESCRIPTION
**Pull request by gretard**
Changes:

- Added test library for mocking OkHttpClient responses
- Added corporate actions endpoint

### CODE REVIEW

**Comment by Petersoj** [comment]
@gretard thank you for your contribution! I will review this and publish a release soon.

**Comment by gretard** [comment]
Thank you for maintaining such wonderful library. I am sorry for not raising another PR, but I have updated this branch to include news endpoint and news streaming client.

**Comment by Petersoj** [comment]
Thanks for your kind words and your contribution! I appreciate it.
I will review these changes soon.

**Comment by Petersoj** [comment]
I've modified this PR to account for transitioning the RestAPI portion of this library to OpenAPI generated clients and to drop RestAPI unit testing. I will keep the changes relating to the websocket streaming endpoints.
Thanks for your contribution!

**Pull request merged**
